### ISSUE TITLE
Crash on Xamarin forms

### ISSUE THREAD

**Issue by sherifawad** [Strumenta/SmartReader#18]
Thanx for your great efforts.
I tried to check the project against Xamarin Forms. But using it throw result in crash and an error.

> Message = "Method not found: 'AngleSharp.IConfiguration AngleSharp.CssConfigurationExtensions.WithCss(AngleSharp.IConfiguration, AngleSharp.Css.Parser.CssParserOptions, System.Action`1<AngleSharp.Css.CssStylingService>)'."

But if I use the source code it works Perfectly.

**Comment by unosviluppatore** [comment]
Thanks for the feedback. I will try to check the issue this weekend.

**Comment by unosviluppatore** [comment]
I am not an expert in Xamarin Forms, however I have tried a sample project and it works with the latest release of the library. What version of Xamarin Forms and SmartReader are you using? Are you running it on a real device or an emulator?

**Comment by sherifawad** [comment]
[https://github.com/sherifawad/WebViewSample](url)

**Comment by unosviluppatore** [comment]
That example does work, even after I removed the SmartReader source, but I think I find the issue. The dependencies on the published version of SmartReader are wrong: it depends on AngleSharp (>= 0.11.0), but AngleSharp.Css (>=0.10.0). I am not sure how that happened.

However, you have other packages in our app that updates AngleSharp.Css to the latest version, so I think that with the other dependencies it bypasses the issue. I will release a new version soon and this should solve this issue.
