### ISSUE TITLE
does it work on .NET Framework 4.6?

### ISSUE THREAD

**Issue by yasindn** [Strumenta/SmartReader#2]
Hi
I have problem with smartreader in my project.
I test it in .net core and it's fine but when create project in .net framework it's not work?
can you help me?

**Comment by unosviluppatore** [comment]
It is a [.NET Standard 1.3 library](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md) so it should work on .NET Framework 4.6. Can you tell me if it does not work for a particular url or for every url you have tried?

**Comment by yasindn** [comment]
it's not work for any URL
when call ParseArticle, app wait on this line and no error and no progress

**Comment by unosviluppatore** [comment]
Strange, since it does work on my tests. I will do more testing and get back to you.

**Comment by yasindn** [comment]
Tanks lot,
I test it on consoleapp .net framework and it does work fine. but still problem in webapp .net framework.
can you send me your webapp test?

**Comment by yasindn** [comment]
Hi again
Can you add asp.net framework project file to Demo?
I do everything but didn't get any response.

**Comment by yasindn** [comment]
I found problem in code by trace it.
the problem is

`private async Task<Stream> GetStreamAsync(Uri resource)
		{
			using (HttpClient hc = new HttpClient())
			{
				var response = await hc.GetAsync(resource);`
GetAsync is deadlock!

here is description to solve it. I applied 1st practice and it's solve problem. but 2nd practice is better
[http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html](url)

**Comment by unosviluppatore** [comment]
Thanks for your help. I will fix it in the next release and change the API to offer a completely asynchronous option.
