### ISSUE TITLE
Add extract Twitter embed and youtube video. Please!

### ISSUE THREAD

**Issue by taavandais2** [Strumenta/SmartReader#24]
like a title!!!!!!!!!!

**Comment by gabriele-tomassetti** [comment]
The algorithm already keeps embedded Youtube videos. Are you asking for something like a property `Videos` or `Tweets` on the `Article` object? Or are you thinking about something like a method `GetVideosAsync()`?

**Comment by taavandais2** [comment]
thank you!!!!!
