### ISSUE TITLE
Is there a way to get the full html text of an article? (from the <htm> or <body> tag)?

### ISSUE THREAD

**Issue by trescatorce** [Strumenta/SmartReader#25]
Is there a way to get the full html text of an article? (from the 'html' or '<body' tags), as **article1.content** ?

I am interested in being able to extract before the content all the urls that include the full text.

Thank one thousand thanks in advance

**Comment by gabriele-tomassetti** [comment]
There is no simple way to get the HTML directly as the content. However, you could use a [custom operation at the start](https://smartreader.inre.me/articles/advanced.html#adding-custom-operations).  The custom operation will receive all the original HTML, so you can then extract all the urls from the article before the content is parsed.

**Comment by trescatorce** [comment]
Thank you!
I just did this dirty source to add in an array all text.

```
private static void ReaderExFullHtml(AngleSharp.Dom.IElement element)
{
    PBEx.PBIDObject[CurrentID].AllHtml = element.OuterHtml;
}
```
mutReaderEx.WaitOne();
CurrentID = ID;
PBEx.PBIDObject[ID].ReaderEx.AddCustomOperationStart(ReaderExFullHtml);
mutReaderEx.ReleaseMutex();`
