### ISSUE TITLE
Angle Sharp parsing xml attributes

### ISSUE THREAD

**Issue by prestonkell** [Strumenta/SmartReader#42]
Hi there, 
I'm seeing a number of pages that throw `Invalid character detected. AngleSharp.Dom.DomException` because AngleSharp's attributes get validated with their `IsXmlName` and `IsXmlNameStart` method https://github.com/AngleSharp/AngleSharp/blob/cdc88b1c0e71476f35fe9405d38b66e33fa1969c/src/AngleSharp/Text/XmlExtensions.cs#L47.

It's called from the `SimplifyNestedElements` method in Readability when setting attributes `https://github.com/Strumenta/SmartReader/blob/master/src/SmartReader/Readability.cs#L190`.

Can this be optional or somehow be cleaned or something in order to avoid these errors? I've seen this with attributes that start with '@' or other chars that xml deems wrong but are in html.

**Comment by gabriele-tomassetti** [comment]
Thanks for the bug report and the investigation regarding the cause. I am going to try solving the issue this weekend.

**Comment by gabriele-tomassetti** [comment]
@prestonkell I cannot reproduce this issue. Could you provide an example HTML page that generate this error?

**Comment by prestonkell** [comment]
Yeah no problem - I get the error with this site: https://www.mumsnet.com/talk/parenting/4301360-second-child-looks-more-like-mum
