### ISSUE TITLE
Memory leak on undisposed doc within Reader

### ISSUE THREAD

**Issue by Joshhua5** [Strumenta/SmartReader#50]
The Reader class creates a IHtmlDocument object which needs to be disposed of.

Workaround using reflection. 
(typeof(Reader).GetField("doc", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(reader) as IHtmlDocument)?.Dispose();

**Comment by gabriele-tomassetti** [comment]
Thanks for the bug report. I am going to fix it this weekend.
