### ISSUE TITLE
Undisposed StreamWriter in Article.ConvertToPlaintext 

### ISSUE THREAD

**Issue by Joshhua5** [Strumenta/SmartReader#51]
Hey, still hunting for memory leaks, found this one. 

https://github.com/Strumenta/SmartReader/blob/master/src/SmartReader/Article.cs#L228

**Comment by gabriele-tomassetti** [comment]
Thanks for the bug report. I am going to fix it this weekend. If you let me know when you have completed your analysis I will release a new version.

**Comment by Joshhua5** [comment]
This is all I found when looking for memory leaks in my application, thanks for being responsive and translating this project to C#.
