### ISSUE TITLE
data URIs in IMG SRC not preserved, treated as relative URL and resolved to invalid URL

### ISSUE THREAD

**Issue by acidus99** [Strumenta/SmartReader#58]
[This article](https://www.businessinsider.com/ukraine-war-putin-russia-nuclear-weapons-threats-what-could-happen-2022-10) contains a `<img>` tag in the article content that should be extracted. The `<img>` tag's `src` attribute uses a `data:` URI to embedded a SVG image as a placeholder:

<img width="940" alt="data-uri" src="https://github.com/Strumenta/SmartReader/assets/4118560/fd33fb7a-7cbd-42f5-8f82-3c38054f045e">

JavaScript later lazy loads the correct image URL into the `src` attribute. I don't really care about that JS execution part. the issue is that the `data:` URL is not preserved when the article is extracted. Instead the `data:` URI is treated as a relative URL, and the extracted article uses the URL `https://www.businessinsider.com/data:image/svg+xml,%3C%3Fxml%20version='1.0'%20encoding='UTF-8'%3F%3E%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20width='1'%20height='1'/%3` as the `src` value instead of the original `data:` URI.

**Comment by gabriele-tomassetti** [comment]
Thanks for the bug report. We should actually [manage the case in which we have a lazy image SVG](https://github.com/Strumenta/SmartReader/blob/40781ed2669c5ca1644a706983600acb0a007c22/src/SmartReader/SmartReader.cs#L1578), so there must be a bug somewhere, maybe in the part where we fix relative URIs.  I will try to fix it this weekend.

**Comment by gabriele-tomassetti** [comment]
For some reason, data uri encoded in UTF-8 are not recognized as well-formed URI by the method [Uri.IsWellFormedUriString](https://learn.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?view=net-7.0), only data uri encoded in base64. So I have added a specific check for them.
