### ISSUE TITLE
Improve extensibility of parser

### ISSUE THREAD

**Issue by kodfodrasz** [Strumenta/SmartReader#6]
Hi!

I find your library pretty useful, but in some cases its behaviour is not completely according to my needs.
While for some points i believe I should send PRs, there are things where being able to customize the parser would be more beneficial.

I do not want to create a fork to tune it to my interests, I believe that some virtual methods would just be fine.

What do you think about it?

Best Regards,
@kodfodrasz

**Comment by unosviluppatore** [comment]
I am always open to improvements. I have no problem accepting changes as long as we can still maintain compatibility with updates in the original mozilla readability library. What do you have in mind?

**Comment by kodfodrasz** [comment]
On one hand I'd like to improve the language detection. Right now I need improvement in that, but I'm about to integrate the lib to and semi-interactively process many sites, so I might find other things also. 

## About language detection
According to [W3](www.w3.org/International/questions/qa-html-language-declarations) `xml:lang` should also be handled. I'll send a PR about it if you don't have time now, as soon as I get there in my project to need the feature.

## About compatibility
I have skimmed over the code, it is not totally C#-sytle. Is it because it is strongly  in sync with the Mozilla code?

Btw the lib is cool, I have tested it and found pretty useful out of the box, but have only done some feasibility study yet.

**Comment by unosviluppatore** [comment]
Thanks for your feedback.
It's true that the code is not perfectly C#-style, you are not the first one to notice. It is both because I try to follow the original library and also because the AngleSharp code follows the JavaScript API. 

**About language detection**

I can add the xml:lang support myself if you can wait for the end of the week.

**Extensibility**

I can add a few properties to handle custom weights. We could handle extensibility by adding the chance to add functions to process data before the [final cleaning of the article]

**Comment by kodfodrasz** [comment]
> you are not the first one to notice

For me the single large class is the most alien, but I have checked the Mozilla code, and I see that it resembles SmartReader very much. But this is highly off topic to extensibility. I can understand this approach. Personally I'd use extension methods and local functions extensively, and link to appropriate mozilla functions via comments, but generally still keep the code very much in sync with upstream.

> I can add the xml:lang support myself if you can wait for the end of the week.

That is sooner than I will likely get there. Thank you very much!

> We could handle extensibility by adding the chance to add functions to process data before the final cleaning of the article.

That would be cool.

Also a way to customize regexps would be nice, as it would help parse pages of local markets without having to fork the project. Eg.: when I'm parsing pages from Hungary and some sites have custom video platform, the videos regexp might be handy if extended with 'indavideo' for example (the platform used by one of the largest Hungarian internet News portal index.hu)

One annother thing: being able to provide the `HttpClient` might be useful, when using the lib in a DI container and having a HttpClient already registered and "warmed up".

I understand that my points might not all make sense for the project, might be specialized for my usecases, and that they might have implications you may not wish to take. I'm mostly brainstorming yet.

**Comment by kodfodrasz** [comment]
A bit of off topic: Regarding C# style I think it should be considered to use C# features more instead of the transpilation of JS code, as for language detection for example

~~~cs
            // added language extraction

            if (String.IsNullOrEmpty(language))
            {
                metadata.Language = doc.GetElementsByTagName("html")[0].GetAttribute("lang");

                if (String.IsNullOrEmpty(metadata.Language))
                {
                    metadata.Language = doc.QuerySelector("meta[http-equiv=\"Content-Language\"]")?.GetAttribute("content");
                    if (String.IsNullOrEmpty(metadata.Language))
                    {
                        // this is wrong, but it's used

                        metadata.Language = doc.QuerySelector("meta[name=\"lang\"]")?.GetAttribute("value");
                        if (String.IsNullOrEmpty(metadata.Language))
                            metadata.Language = "";
                    }
                }
            }
~~~

can be written with C# features as something like:

~~~cs
            // added language extraction
            IEnumerable<string> LanguageHeuristics(){
                yield return language;
                yield return doc.GetElementsByTagName("html")[0].GetAttribute("lang");
                yield return doc.QuerySelector("meta[http-equiv=\"Content-Language\"]")?.GetAttribute("content");
                yield return doc.QuerySelector("meta[name=\"lang\"]")?.GetAttribute("value");
            }

            metadata.Language = LanguageHeuristics().FirstOrDefault(l => !String.IsNullOrEmpty(l)) ?? "";
~~~

but this is just a sidenote.

**Comment by kodfodrasz** [comment]
One more idea about extensibility: I think it would be a handy alternative to to using a TextWriter for logging to be able to provide an Action<string>, which one could directly bind to either a textwriter, or a logging framework.

I have seen this approach used by [Evolve DB migration tool](https://evolve-db.netlify.com/getting-started/#in-app-mode) and IMHO it is the best approach I saw so far. (better than forcing the user to use specific logging facedes)

Best Regards,
@kodfodrasz

**Comment by unosviluppatore** [comment]
You have a lot of good ideas. Let me think about them a bit.

**Comment by unosviluppatore** [comment]
I have added the support for the xml:tag in the last modifications, but the changes are only on GitHub for now, not yet on nuget. That's because I want to see if I can implement your other suggestions before publishing a new version.

**Comment by kodfodrasz** [comment]
Thank you. I'm sure you can do them, the question is if you see them worth given the project's goals, and API compatibility.

Thank you for the great support!

**Comment by unosviluppatore** [comment]
I have added some of your suggestions. I am still working on your logging suggestion. Sorry, for the long wait, but I was occupied with work.

It took me a lot of time also because I was trying to implement a language identification feature, [based on the actual text](https://en.wikipedia.org/wiki/Language_identification) but I had to set it aside. Maybe I will add it in a separate library.

**Comment by GKersten** [comment]
@unosviluppatore I just found out about this library and I really like it. I read about providing better extensibility in this issue. And at this point I have a specific case where I am not sure what would be the best approach:

For our project we try to get the text content from articles from multiple news websites. For a big part the right content gets extracted correctly, but not entirely and I am trying to fine tune per website.

You already did some nice work with with the `CustomOperations `and `AddOptionToRegularExpression`, however I am having some issues with it. The problem being:

In side the article there is an element at the end:
`<div classname="author-bio"><p>...some text here </p></div>`

After the SmartReader did it's processing the text is still in the article as expected. However the div with it's classname gets removed. This gets done before the RegularExpressions gets applied, so my regular expression has no effect:
`reader.AddOptionToRegularExpression(Reader.RegularExpressions.Negative, "author-bio");`

For now I am trying to do some manual searching for the specific text in the CustomOperations, but it is very hard to find that text when the div and it's classname is not present anymore.

What would be your approach?

**Comment by unosviluppatore** [comment]
Thanks for the appreciation! 
Your issue is due the algorithm itself: inside the function` GrabArticle` there is a section that handle DIVs: `// Turn all divs that don't have children block level elements into p's`.

Your problem is caused by this specific part:
```
// Sites like http://mobile.slate.com encloses each paragraph with a DIV
// element. DIVs with only a P element inside and no text content can be
// safely converted into plain P elements to avoid confusing the scoring
// algorithm with DIVs with are, in practice, paragraphs.
if (HasSingleTagInsideElement(node, "P") && GetLinkDensity(node) < 0.25)
{
    var newNode = node.Children[0];
    node.Parent.ReplaceChild(newNode, node);
    node = newNode;
    elementsToScore.Add(node);
}
```
Basically, every DIV that has just one P element gets removed.

If it is feasible to you, you can

**Comment by kodfodrasz** [comment]
Hi!

Sorry for the later reply, I was also pretty occupied with other works.

The changes look very nice. As winter is coming I'll continue my work on the project where I used SmartReader, and will make use of the new features!

Best Regards,
@kodfodrasz
