### ISSUE TITLE
Lack of user-agent when sending request.

### ISSUE THREAD

**Issue by AndySchmitt** [Strumenta/SmartReader#9]
Its my first time describing an issue in GitHub, and I don't know if I'm doing this the correct way.

When sending a request with HttpClient, SmartReader does not inform the user-agent header, this causes a "403 forbidden" response in some cases.

Here is a test case: 
https://politica.estadao.com.br/blogs/fausto-macedo/operacao-descarte-ataca-fraude-e-lavagem-de-dinheiro-em-sp-e-minas/

**Comment by unosviluppatore** [comment]
Thanks for indicating the problem. Yes, this is the correct way of describing an issue for this project.

I will fix it this weekend.

**Comment by unosviluppatore** [comment]
This has been fixed by commit [Setting default user agent](https://github.com/Strumenta/SmartReader/commit/d013371b9face2466504b61206862fe574fac82c)
